### ISSUE TITLE
build error 

### ISSUE THREAD

**Issue by superbderrick** [robsondepaula/unity-android-native-camera#2]
Hi Robsondepaula,

when I tried to build your demo project, it showed build error which is  regarding of Dex problem.

Any idea to fix build error? 

I have test with latest unity 

Thanks
Regrads,

com.android.build.api.transform.TransformException: java.lang.RuntimeException: java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives: /Users/derrick/temp/unity-android-native-camera/UnityAndroidCamera/Temp/gradleOut/build/intermediates/transforms/dexBuilder/release/12, /Users/derrick/temp/unity-android-native-camera/UnityAndroidCamera/Temp/gradleOut/build/intermediates/transforms/externalLibsDexMerger/release/0 See the Console for details.

**Comment by robsondepaula** [comment]
Hello @superbderrick,

Please open "Build Settings" and make sure:
-  "Android" is selected in the Platform panel;
-  the Build System dropbox is showing "Internal".

This should allow you to build successfully.

**Comment by superbderrick** [comment]
Thanks, build is working well but camera preview was not showing.
Anyway thanks the project is very helpful
Thanks
Regards
