### ISSUE TITLE
How to render SurfaceTexture content into Unity via FBO?

### ISSUE THREAD

**Issue by waynehan-lab** [robsondepaula/unity-android-native-camera#3]
I have been working on related projects recently. Searching on Google search uses FBO to achieve this effect. What should I do?

**Comment by robsondepaula** [comment]
Hi @hywenbinger,

Unfortunatelly I'm out of cycles to work on new requests but can try to provide some suggestions. Can you share your use case?

This repo shares a specific need in which I had to intercept the Android camera pixels, modify it and later display in Unity.

Depending on what you need to achieve some layers of this solution are optional.

**Comment by waynehan-lab** [comment]
Hi @robsondepaula 

Thank you very much for your reply, your project gave me some inspiration.

I have uploaded the demo to github, the URL is [https://github.com/hywenbinger/android_unity_video](https://github.com/hywenbinger/android_unity_video).

In my demo, I can already show the video through a shader.
I need to get Texture2D to do some other processing on the image, but for now I can only get the external texture.
Some people suggest that can use FBO to achieve the effect of oes->fbo->2d, but my opengl is not very good. Can you give some suggestions?

**Comment by robsondepaula** [comment]
Hello @hywenbinger,

Nice of you to upload your demo. It looks neat.

I could take a quick look and noticed you are creating the texture on the Android Plugin. I recall that when I was working on the unity camera plugin I couldn't modify the Texture2D if I created it the same way you are doing. 

What worked is the flow you can verify in the code that I shared:

1. The Texture2D is created on Unity (CameraPluginWrapper.cs).
2. A pointer to this Texture2D is passed to a low level Android plugin (RenderingPlugin.cpp) using GetNativeTexturePtr(). With this value, OnRenderEvent() will call a regular Android plugin (CameraPluginActivity.java).
3. Each call made by the low level plugin will end up calling requestJavaRendering() on the regular Android plugin.
4. Finally the regular Android plugin updates the Texture2D.

Although the architecture may look awkward, it is what produced the result I needed.

One thing I could suggest is that you try this flow and see if it unblocks you before having to ramp-up on OpenGL (I'm also not skilled on it).

**Comment by waynehan-lab** [comment]
Hi @robsondepaula ,   

Thank you very much for your suggestion, I will try it according to your project.
